config/routes.rb
Rails.application.routes.draw do
  	resources :workpermits do
  		get 'altedit', :on => :member
	end
  	resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/workpermit.rb
class Workpermit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/workpermits_controller.rb
class WorkpermitsController < ApplicationController
  before_action :set_workpermit, only: [:show, :edit, :update, :destroy, :altedit]

  # GET /workpermits
  # GET /workpermits.json
  def index
    @workpermits = Workpermit.all
  end

  # GET /workpermits/1
  # GET /workpermits/1.json
  def show
  end

  # GET /workpermits/new
  def new
    @workpermit = Workpermit.new
  end

  # GET /workpermits/1/edit
  def edit
  end

  # GET /workpermits/1/altedit
  def altedit
      
  end

  # POST /workpermits
  # POST /workpermits.json
  def create
    @workpermit = Workpermit.new(workpermit_params)

    respond_to do |format|
      if @workpermit.save
        format.html { redirect_to @workpermit, notice: 'Workpermit was successfully created.' }
        format.json { render :show, status: :created, location: @workpermit }
      else
        format.html { render :new }
        format.json { render json: @workpermit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workpermits/1
  # PATCH/PUT /workpermits/1.json
  def update
    respond_to do |format|
      if @workpermit.update(workpermit_params)
        format.html { redirect_to @workpermit, notice: 'Workpermit was successfully updated.' }
        format.json { render :show, status: :ok, location: @workpermit }
      else
        format.html { render :edit }
        format.json { render json: @workpermit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workpermits/1
  # DELETE /workpermits/1.json
  def destroy
    @workpermit.destroy
    respond_to do |format|
      format.html { redirect_to workpermits_url, notice: 'Workpermit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workpermit
      @workpermit = Workpermit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workpermit_params
      params.fetch(:workpermit, {}).permit(:first_name, :last_name, :status, :start_date, :end_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workpermits_helper.rb
module WorkpermitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/workpermits/_form.html.erb
<%= form_with(model: workpermit, local: true) do |form| %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>First Name</td>
      <td>Last Name</td>
      <td>Start Date</td>
      <td>End Date</td>
      <td>Status</td>
    </tr>
    <tr>
      <td><%= text_field :workpermit, :first_name %> </td>
      <td><%= text_field :workpermit, :last_name %> </td>
      <td><%= text_field :workpermit, :start_date %> </td>
      <td><%= text_field :workpermit, :end_date %> </td>
      <td><%= text_field :workpermit, :status %> </td>
    <tr>
</tbody>
</table>
  <% if workpermit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workpermit.errors.count, "error") %> prohibited this workpermit from being saved:</h2>

      <ul>
      <% workpermit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/workpermits/altedit.html.erb
<h1>Alt Edit Workpermit</h1>

<%= render 'form', workpermit: @workpermit %>

<%= link_to 'Show', @workpermit %> |
<%= link_to 'Back', workpermits_path %>

app/views/workpermits/edit.html.erb
<h1>Editing Workpermit</h1>

<%= render 'form', workpermit: @workpermit %>

<%= link_to 'Show', @workpermit %> |
<%= link_to 'Back', workpermits_path %>

app/views/workpermits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workpermits</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workpermits.each do |workpermit| %>
      <tr>
          <td><b>First Name</b></td>
          <td><b>Last Name</b></td>
          <td><b>Status</b></td>
          <td colspan="=3"><b>Actions</b></td>
      </tr>
      <tr>
        <td><%= workpermit.first_name %></td>
          <td><%= workpermit.last_name %></td>
          <td><%= workpermit.status %></td>
        <td><%= link_to 'Show', workpermit %></td>
        <td><%= link_to 'Edit', edit_workpermit_path(workpermit) %></td>
        <td><%= link_to 'Destroy', workpermit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workpermit', new_workpermit_path %>

app/views/workpermits/new.html.erb
<h1>New Workpermit</h1>

<%= render 'form', workpermit: @workpermit %>

<%= link_to 'Back', workpermits_path %>

app/views/workpermits/show.html.erb
<p id="notice"><%= notice %></p>
First Name <%= @workpermit.first_name %> <br>
Last Name <%= @workpermit.last_name %> <br>
Start Date <%= @workpermit.start_date %> <br>
End Date <%= @workpermit.end_date %> <br>
Status <%= @workpermit.status %> <br> <br>
<%= link_to 'Edit', altedit_workpermit_path(@workpermit) %> |
<%= link_to 'Back', workpermits_path %>